meta:
  environment: etcd-warden

  stemcell:
    name: bosh-stemcell
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: etcd_leader_z1
    instances: 1
    networks:
      - name: etcd1
        static_ips: (( static_ips(1) ))
  - name: etcd_z1
    instances: 2
    networks:
      - name: etcd1
        static_ips: (( static_ips(2,3) ))
    properties:
      etcd:
        leader_address: (( jobs.etcd_leader_z1.networks.etcd1.static_ips.[0] ))

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: etcd1
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.0.0/30
    reserved:
    - 10.244.0.1
    static:
    - 10.244.0.2
  - cloud_properties:
      name: random
    range: 10.244.0.4/30
    reserved:
    - 10.244.0.5
    static:
    - 10.244.0.6
  - cloud_properties:
      name: random
    range: 10.244.0.8/30
    reserved:
    - 10.244.0.9
    static:
    - 10.244.0.10
  - cloud_properties:
      name: random
    range: 10.244.0.12/30
    reserved:
    - 10.244.0.13
    static:
    - 10.244.0.14
  - cloud_properties:
      name: random
    range: 10.244.0.16/30
    reserved:
    - 10.244.0.17
    static:
    - 10.244.0.18
  - cloud_properties:
      name: random
    range: 10.244.0.20/30
    reserved:
    - 10.244.0.21
    static:
    - 10.244.0.22
  - cloud_properties:
      name: random
    range: 10.244.0.24/30
    reserved:
    - 10.244.0.25
    static:
    - 10.244.0.26
  - cloud_properties:
      name: random
    range: 10.244.0.28/30
    reserved:
    - 10.244.0.29
    static:
    - 10.244.0.30
  - cloud_properties:
      name: random
    range: 10.244.0.32/30
    reserved:
    - 10.244.0.33
    static:
    - 10.244.0.34
  - cloud_properties:
      name: random
    range: 10.244.0.36/30
    reserved:
    - 10.244.0.37
    static:
    - 10.244.0.38
  - cloud_properties:
      name: random
    range: 10.244.0.40/30
    reserved:
    - 10.244.0.41
    static:
    - 10.244.0.42
  - cloud_properties:
      name: random
    range: 10.244.0.44/30
    reserved:
    - 10.244.0.45
    static:
    - 10.244.0.46
  - cloud_properties:
      name: random
    range: 10.244.0.48/30
    reserved:
    - 10.244.0.49
    static:
    - 10.244.0.50
  - cloud_properties:
      name: random
    range: 10.244.0.52/30
    reserved:
    - 10.244.0.53
    static:
    - 10.244.0.54
  - cloud_properties:
      name: random
    range: 10.244.0.56/30
    reserved:
    - 10.244.0.57
    static:
    - 10.244.0.58
  - cloud_properties:
      name: random
    range: 10.244.0.60/30
    reserved:
    - 10.244.0.61
    static:
    - 10.244.0.62
  - cloud_properties:
      name: random
    range: 10.244.0.64/30
    reserved:
    - 10.244.0.65
    static:
    - 10.244.0.66
  - cloud_properties:
      name: random
    range: 10.244.0.68/30
    reserved:
    - 10.244.0.69
    static:
    - 10.244.0.70
  - cloud_properties:
      name: random
    range: 10.244.0.72/30
    reserved:
    - 10.244.0.73
    static:
    - 10.244.0.74
  - cloud_properties:
      name: random
    range: 10.244.0.76/30
    reserved:
    - 10.244.0.77
    static:
    - 10.244.0.78
  - cloud_properties:
      name: random
    range: 10.244.0.80/30
    reserved:
    - 10.244.0.81
    static:
    - 10.244.0.82
  - cloud_properties:
      name: random
    range: 10.244.0.84/30
    reserved:
    - 10.244.0.85
    static:
    - 10.244.0.86
  - cloud_properties:
      name: random
    range: 10.244.0.88/30
    reserved:
    - 10.244.0.89
    static:
    - 10.244.0.90
  - cloud_properties:
      name: random
    range: 10.244.0.92/30
    reserved:
    - 10.244.0.93
    static:
    - 10.244.0.94
  - cloud_properties:
      name: random
    range: 10.244.0.96/30
    reserved:
    - 10.244.0.97
    static:
    - 10.244.0.98
  - cloud_properties:
      name: random
    range: 10.244.0.100/30
    reserved:
    - 10.244.0.101
    static:
    - 10.244.0.102
  - cloud_properties:
      name: random
    range: 10.244.0.104/30
    reserved:
    - 10.244.0.105
    static:
    - 10.244.0.106
  - cloud_properties:
      name: random
    range: 10.244.0.108/30
    reserved:
    - 10.244.0.109
    static:
    - 10.244.0.110
  - cloud_properties:
      name: random
    range: 10.244.0.112/30
    reserved:
    - 10.244.0.113
    static:
    - 10.244.0.114
  - cloud_properties:
      name: random
    range: 10.244.0.116/30
    reserved:
    - 10.244.0.117
    static:
    - 10.244.0.118
  - cloud_properties:
      name: random
    range: 10.244.0.120/30
    reserved:
    - 10.244.0.121
    static:
    - 10.244.0.122
  - cloud_properties:
      name: random
    range: 10.244.0.124/30
    reserved:
    - 10.244.0.125
    static:
    - 10.244.0.126
  - cloud_properties:
      name: random
    range: 10.244.0.128/30
    reserved:
    - 10.244.0.129
    static:
    - 10.244.0.130
  - cloud_properties:
      name: random
    range: 10.244.0.132/30
    reserved:
    - 10.244.0.133
    static:
    - 10.244.0.134
  - cloud_properties:
      name: random
    range: 10.244.0.136/30
    reserved:
    - 10.244.0.137
    static:
    - 10.244.0.138
  - cloud_properties:
      name: random
    range: 10.244.0.140/30
    reserved:
    - 10.244.0.141
    static:
    - 10.244.0.142
  - cloud_properties:
      name: random
    range: 10.244.0.144/30
    reserved:
    - 10.244.0.145
    static:
    - 10.244.0.146
  - cloud_properties:
      name: random
    range: 10.244.0.148/30
    reserved:
    - 10.244.0.149
    static:
    - 10.244.0.150
  - cloud_properties:
      name: random
    range: 10.244.0.152/30
    reserved:
    - 10.244.0.153
    static:
    - 10.244.0.154
  - cloud_properties:
      name: random
    range: 10.244.0.156/30
    reserved:
    - 10.244.0.157
    static:
    - 10.244.0.158
  - cloud_properties:
      name: random
    range: 10.244.0.160/30
    reserved:
    - 10.244.0.161
    static:
    - 10.244.0.162
  - cloud_properties:
      name: random
    range: 10.244.0.164/30
    reserved:
    - 10.244.0.165
    static:
    - 10.244.0.166
  - cloud_properties:
      name: random
    range: 10.244.0.168/30
    reserved:
    - 10.244.0.169
    static:
    - 10.244.0.170
  - cloud_properties:
      name: random
    range: 10.244.0.172/30
    reserved:
    - 10.244.0.173
    static:
    - 10.244.0.174
  - cloud_properties:
      name: random
    range: 10.244.0.176/30
    reserved:
    - 10.244.0.177
    static:
    - 10.244.0.178
  - cloud_properties:
      name: random
    range: 10.244.0.180/30
    reserved:
    - 10.244.0.181
    static:
    - 10.244.0.182
  - cloud_properties:
      name: random
    range: 10.244.0.184/30
    reserved:
    - 10.244.0.185
    static:
    - 10.244.0.186
  - cloud_properties:
      name: random
    range: 10.244.0.188/30
    reserved:
    - 10.244.0.189
    static:
    - 10.244.0.190
  - cloud_properties:
      name: random
    range: 10.244.0.192/30
    reserved:
    - 10.244.0.193
    static:
    - 10.244.0.194
  - cloud_properties:
      name: random
    range: 10.244.0.196/30
    reserved:
    - 10.244.0.197
    static:
    - 10.244.0.198
  - cloud_properties:
      name: random
    range: 10.244.0.200/30
    reserved:
    - 10.244.0.201
    static:
    - 10.244.0.202
  - cloud_properties:
      name: random
    range: 10.244.0.204/30
    reserved:
    - 10.244.0.205
    static:
    - 10.244.0.206
  - cloud_properties:
      name: random
    range: 10.244.0.208/30
    reserved:
    - 10.244.0.209
    static:
    - 10.244.0.210
  - cloud_properties:
      name: random
    range: 10.244.0.212/30
    reserved:
    - 10.244.0.213
    static:
    - 10.244.0.214
  - cloud_properties:
      name: random
    range: 10.244.0.216/30
    reserved:
    - 10.244.0.217
    static:
    - 10.244.0.218
  - cloud_properties:
      name: random
    range: 10.244.0.220/30
    reserved:
    - 10.244.0.221
    static:
    - 10.244.0.222
  - cloud_properties:
      name: random
    range: 10.244.0.224/30
    reserved:
    - 10.244.0.225
    static:
    - 10.244.0.226
  - cloud_properties:
      name: random
    range: 10.244.0.228/30
    reserved:
    - 10.244.0.229
    static:
    - 10.244.0.230
  - cloud_properties:
      name: random
    range: 10.244.0.232/30
    reserved:
    - 10.244.0.233
    static:
    - 10.244.0.234
  - cloud_properties:
      name: random
    range: 10.244.0.236/30
    reserved:
    - 10.244.0.237
    static:
    - 10.244.0.238
  - cloud_properties:
      name: random
    range: 10.244.0.240/30
    reserved:
    - 10.244.0.241
    static:
    - 10.244.0.242
  - cloud_properties:
      name: random
    range: 10.244.0.244/30
    reserved:
    - 10.244.0.245
    static:
    - 10.244.0.246
  - cloud_properties:
      name: random
    range: 10.244.0.248/30
    reserved:
    - 10.244.0.249
    static:
    - 10.244.0.250
  - cloud_properties:
      name: random
    range: 10.244.0.252/30
    reserved:
    - 10.244.0.253
    static:
    - 10.244.0.254
  - cloud_properties:
      name: random
    range: 10.244.1.0/30
    reserved:
    - 10.244.1.1
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.4/30
    reserved:
    - 10.244.1.5
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.8/30
    reserved:
    - 10.244.1.9
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.12/30
    reserved:
    - 10.244.1.13
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.16/30
    reserved:
    - 10.244.1.17
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.20/30
    reserved:
    - 10.244.1.21
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.24/30
    reserved:
    - 10.244.1.25
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.28/30
    reserved:
    - 10.244.1.29
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.32/30
    reserved:
    - 10.244.1.33
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.36/30
    reserved:
    - 10.244.1.37
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.40/30
    reserved:
    - 10.244.1.41
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.44/30
    reserved:
    - 10.244.1.45
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.48/30
    reserved:
    - 10.244.1.49
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.52/30
    reserved:
    - 10.244.1.53
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.56/30
    reserved:
    - 10.244.1.57
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.60/30
    reserved:
    - 10.244.1.61
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.64/30
    reserved:
    - 10.244.1.65
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.68/30
    reserved:
    - 10.244.1.69
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.72/30
    reserved:
    - 10.244.1.73
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.76/30
    reserved:
    - 10.244.1.77
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.80/30
    reserved:
    - 10.244.1.81
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.84/30
    reserved:
    - 10.244.1.85
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.88/30
    reserved:
    - 10.244.1.89
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.92/30
    reserved:
    - 10.244.1.93
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.96/30
    reserved:
    - 10.244.1.97
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.100/30
    reserved:
    - 10.244.1.101
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.104/30
    reserved:
    - 10.244.1.105
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.108/30
    reserved:
    - 10.244.1.109
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.112/30
    reserved:
    - 10.244.1.113
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.116/30
    reserved:
    - 10.244.1.117
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.120/30
    reserved:
    - 10.244.1.121
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.124/30
    reserved:
    - 10.244.1.125
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.128/30
    reserved:
    - 10.244.1.129
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.132/30
    reserved:
    - 10.244.1.133
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.136/30
    reserved:
    - 10.244.1.137
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.140/30
    reserved:
    - 10.244.1.141
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.144/30
    reserved:
    - 10.244.1.145
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.148/30
    reserved:
    - 10.244.1.149
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.152/30
    reserved:
    - 10.244.1.153
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.156/30
    reserved:
    - 10.244.1.157
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.160/30
    reserved:
    - 10.244.1.161
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.164/30
    reserved:
    - 10.244.1.165
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.168/30
    reserved:
    - 10.244.1.169
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.172/30
    reserved:
    - 10.244.1.173
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.176/30
    reserved:
    - 10.244.1.177
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.180/30
    reserved:
    - 10.244.1.181
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.184/30
    reserved:
    - 10.244.1.185
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.188/30
    reserved:
    - 10.244.1.189
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.192/30
    reserved:
    - 10.244.1.193
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.196/30
    reserved:
    - 10.244.1.197
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.200/30
    reserved:
    - 10.244.1.201
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.204/30
    reserved:
    - 10.244.1.205
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.208/30
    reserved:
    - 10.244.1.209
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.212/30
    reserved:
    - 10.244.1.213
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.216/30
    reserved:
    - 10.244.1.217
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.220/30
    reserved:
    - 10.244.1.221
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.224/30
    reserved:
    - 10.244.1.225
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.228/30
    reserved:
    - 10.244.1.229
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.232/30
    reserved:
    - 10.244.1.233
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.236/30
    reserved:
    - 10.244.1.237
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.240/30
    reserved:
    - 10.244.1.241
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.244/30
    reserved:
    - 10.244.1.245
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.248/30
    reserved:
    - 10.244.1.249
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.252/30
    reserved:
    - 10.244.1.253
    static: []
