meta:
  environment: etcd-aws

  stemcell:
    name: bosh-aws-xen-ubuntu
    version: latest

  discovery_uri: (( merge ))

  security_groups:
  - etcd

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: etcd_z1
    instances: 3
    networks:
      - name: etcd1
        static_ips: ~
    properties:
      etcd:
        discovery_uri: (( meta.discovery_uri ))

compilation:
  cloud_properties:
    instance_type: m1.small

resource_pools:
  - name: small_z1
    cloud_properties:
      instance_type: m1.small

properties:
  networks:
    apps: etcd1

networks:
  - name: floating
    type: vip
    cloud_properties: {}
  - name: etcd1
    type: dynamic
    cloud_properties:
      security_groups: (( meta.security_groups ))
